#!/bin/sh
source ~/.config/i3blocks/scripts/gradation
mem_avail=`free | grep Mem | awk '{print $7}'`
mem_total=`free | grep Mem | awk '{print $2}'`
mem_used=`echo $(( $mem_total - $mem_avail ))`
rate=`echo "100 * $mem_used / $mem_total" | bc`
used=`echo "scale=2;$mem_used/1024/1024" | bc | sed -e 's/^\./0./g'`G
total=`echo "scale=2;$mem_total/1024/1024" | bc`G
echo "$used/$total"
echo "$used/$total"
gradate ffffff ff5717 100 $rate
